import mesa

# Mesa server parameters for use with ModularServer
model_params_mesa = {
    "width": mesa.visualization.Slider(
        name="Grid Width",
        value=100,
        min_value=40,
        max_value=200,
        step=10,
        description="Square Grid Size",
    ),
    "height": mesa.visualization.Slider(
        name="Grid Height",
        value=100,
        min_value=40,
        max_value=200,
        step=10,
        description="Square Grid Size",
    ),
    "wall_thickness": mesa.visualization.Slider(
        name="Wall Thickness",
        value=5,
        min_value=4,
        max_value=20,
        step=1,
        description="Outer Wall Thickness",
    ),
    "sidewalk_ring_width": mesa.visualization.Slider(
        name="Sidewalk Ring Width",
        value=2,
        min_value=1,
        max_value=10,
        step=1,
        description="Sidewalk Ring Width",
    ),
    "ring_road_type": mesa.visualization.Choice(
        name="Ring Road Type",
        value="R2",
        choices=["R1", "R2", "R3"],
        description="Ring Road Type",
    ),
    "min_block_spacing": mesa.visualization.Slider(
        name="Minimum Block Size",
        value=8,
        min_value=3,
        max_value=12,
        step=1,
        description="Minimum Block Size",
    ),
    "max_block_spacing": mesa.visualization.Slider(
        name="Maximum Block Size",
        value=16,
        min_value=8,
        max_value=24,
        step=1,
        description="Max Block Size",
    ),
    "optimized_intersections": mesa.visualization.Checkbox(
        name="Optimized Intersections",
        value=True,
        description="Optimized Intersections",
    ),
    "empty_block_chance": mesa.visualization.Slider(
        name="Empty Block Chance",
        value=0.1,
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        description="Empty Block Chance",
    ),
    "carve_subblock_roads": mesa.visualization.Checkbox(
        name="Carve Subblock Roads",
        value=True,
        description="Carve Subblock Roads",
    ),
    "subblock_roads_have_intersections": mesa.visualization.Checkbox(
        name="Subblock Roads Have Intersections",
        value=False,
        description="Subblock Roads Have Intersections",
    ),
    "min_subblock_spacing": mesa.visualization.Slider(
        name="Minimum Subblock Spacing",
        value=4,
        min_value=2,
        max_value=8,
        step=1,
        description="Minimum Subblock Spacing",
    ),
    "highway_offset_from_edges": mesa.visualization.Slider(
        name="Highway Offset From Edges",
        value=5,
        min_value=0,
        max_value=20,
        step=1,
        description="Highway Offset From Edges",
    ),
    "traffic_light_range": mesa.visualization.Slider(
        name="Traffic Light Range",
        value=4,
        min_value=0,
        max_value=20,
        step=1,
        description="The range up to which the traffic light, is aware of traffic",
    ),
}
